### ISSUE TITLE
not allowing static expense type currency to be different than TA currency

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#84] opened 2017-03-08 21:38 UTC
as discussed in last Budapest meeting - currency for static expenses (terminal, train, air, etc) should be the same as TA currency

**Comment by paragonHex** [comment] 2017-03-20 09:57
Back on trello we had a task very similar to this, so now its locked to local currency. Should it be USD instead, if that is chosen for TA currency?

**Comment by kasfaw** [comment] 2017-03-20 14:38
@paragonHex yes, if the TA currency changes to USD, the currency of the static expense type (train, air, terminal, other) should also change to usd... you essentially want to anchor the static expense type currency to the TA currency

**Comment by janpanchalingam1** [comment] 2017-03-21 17:54
In addition, as per our discussion on March 21 in Budapest, if the traveler is paid in USD and they have unplanned changes that require a second payment, that payment will be in USD. This is the same for travel agencies.

**Comment by aldohunicef** [comment] 2017-04-18 15:59
This needs more clarification from Biz Owners. 

If the desire is to lock the Local Currency for Expenses then currently this is not working. 
However in this card there are multiple versions saying that USD should be included as a currency but at some point there is the instruction to only lock it to Local Currency. 

It seems that it was not clear if the traveler selects USD at the very first time then all the expenses should be inserted in USD, also if the traveler selects Local Currency at the very first time (planning stage) then the expenses should be lock to local currency. Please confirm this scenario @janpanchalingam1 

Also, right now eTools is displaying multiple currencies, even those that are not part of Country Workspaces. Example Argentine Peso and Australian Dollar for Sierra Leone Country Workspace. 

We don't even have an Argentine Workspace or Australian. 
The issue could be related to 283  and 94

**Comment by aldohunicef** [comment] 2017-04-21 19:21
This a slightly different error 

The fields around Expenses need review by Engineers. There is a bug in "Currency"

- As a UNICEF User / Traveller after I select and insert the first field "Expenses type" the drop down menu for currencies becomes a lock field - and I can't select/Change the currency.

This happens for UNICEF User / Traveler.

**Comment by anusenan** [comment] 2017-04-21 19:24
![image](https://cloud.githubusercontent.com/assets/25492170/25292969/91293cf8-26a6-11e7-8adc-fae87f46ec2b.png)
Currencyfield disabled
Role: Unicef user
Workspace: S.Africa

**Comment by anusenan** [comment] 2017-04-21 19:26
![image](https://cloud.githubusercontent.com/assets/25492170/25293003/bfa22f54-26a6-11e7-960d-d4b6affdf099.png)

After refresh, opened a new trip. The currency drop down shows. selected Afghani

**Comment by anusenan** [comment] 2017-04-21 19:26
![image](https://cloud.githubusercontent.com/assets/25492170/25293030/e0a6334e-26a6-11e7-901b-629b8adada15.png)

After selecting currency, I selected expense type. The currency field got disabled again.

**Comment by anusenan** [comment] 2017-04-21 20:21
@robertavram - please update this ticket

**Comment by aldohunicef** [comment] 2017-04-21 20:31
Related, after 3 or 4 rows added then the first expense gets lock

**Comment by aldohunicef** [comment] 2017-04-21 20:32
Related, after 3 or 4 rows added then the first expense gets lock
![image](https://cloud.githubusercontent.com/assets/26142645/25295072/05bf5904-26b0-11e7-86c1-41d3bc514b61.png)

**Comment by torbent** [comment] 2017-04-24 13:33
@aldohunicef @anusenan @janpanchalingam1 @robertavram @ewheeler @ntrncic 
Hi Guys, this card is spanning a few problems.  
The headline is not really related to the issues reported inside the card. "not allowing static expense type currency to be different than TA currency".

The main problem is that there is a bug removing the expense type currency from static expenses, this is caused by the following:
1. Misconfiguration. The travel Expense type should have "user" as vendor number for the static expenses, all the static had something different. This was changed to something different in the past, but the side effect of it only showed up now. This is now corrected on staging. But needs to be changed/validated in production for all static expenses. The "estimate" is also incorrect.  the vendor number in this https://etools-staging.unicef.org/admin/publics/travelexpensetype/5/change/  needs to be empty, which is not allowed in the admin. @robertavram please update that in the DB... also goes for production.
2. Latest permission matrix not deployed. This causes the dropdown to be locked. https://github.com/unicef/etools/pull/599/ 

The two above rendered a situation where the traveler unable to choose currency for the static expenses.
1. is done, 2 is pending on deployment of the PR.
When the PR is merged, all the above scenarios should work according to business req. 

There is however 2 request inside this card that should be broken out of this card and handled as a new features or amendments: 
- Local currencies: Currently there is only one, and when other currencies should be displayed, every currency is displayed. It looks like there is a business need for a subset of local currencies selectable in some cases.
- The title:  "not allowing static expense type currency to be different than TA currency" it's unclear if this is the expected behaviour, or thats the problematic behaviour, it is also not clear if this is relevant for all usertypes or only traveler. A clarification here would be needed to proceed if this is still an issue, or it's handled as a side effect of the other fixes.

**Comment by robertavram** [comment] 2017-04-24 14:21
@torbent @anusenan @janpanchalingam1 
can you provide me with a list of expense types that need to have "user" as the vendor number?
for prod and staging, also expense type with ID 5 needs to be null.. is that correct?

Those issues.. + merging the permission matrix PR needs to solve the issue correct?

On the Permissions Matrix PR... we'd like to have the script that's being used to generate the permissions matrix. Also, the issue connected to it does not reflect how the permissions matrix should have been changed.

Let me know if you need me for anything else...

**Comment by torbent** [comment] 2017-04-24 14:52
@robertavram it's the static ones. I don't have their ID's, but this is how they would look:
- Terminal Cost
- Air Ticket Cost
- Other Traveler Costs
All above should have "user" as vendor.
- Estimated Travel Agent Cost 
Should have "" (empty string) as vendor.

All these except the estimated travel cost is done on staging. Merge the PR should fix the currency lock.

For the permission Matrix PR. The permissions is generated on the frontend, and there is a script that makes it into Yaml. Is that what you need? ... maybe you can address that on the PR directly, so @simon-the-sloth stays in the loop

**Comment by robertavram** [comment] 2017-04-24 15:16
@torbent .. great.. instructions are clear.  on Perm matrix frontend script (with instructions on how to run it) and script to yaml-ize is good for now.. Can @simon-the-sloth point us to it? I've discussed with Simon previously.

**Comment by torbent** [comment] 2017-04-25 10:56
@lordfuoco can you package the frontend script and send it to rob? @simon-the-sloth can you point to the yaml script.

**Comment by lordfuoco** [comment] 2017-04-26 13:37
@torbent @robertavram I prepared a branch that runs the permission matrix editor, I updated the readme in the branch with an explanation on how to use the editor itself:
https://github.com/unicef/etools-t2f/blob/p-matrix-editor/README.md

Once the branch is downloaded it's possible to reach the editor on the url: t2f/permission-matrix-edit

To avoid extra step the editor output  yaml directly ( and convert yaml to JS when importing)

**Comment by janpanchalingam1** [comment] 2017-04-26 18:38
@anusenan @aldohunicef this is fixed and has passed

**Closed** 2017-08-08 14:53 UTC
Labels: bug, Done, High, Maintenance, Trips
