### ISSUE TITLE
New TA Not Required Workflow

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#164] opened 2017-03-21 18:07 UTC

**Comment by kasfaw** [comment] 2017-03-22 08:55
[TA Not Required Workflow.pdf](https://github.com/unicef/etools-issues/files/860840/TA.Not.Required.Workflow.pdf)

**Comment by ewheeler** [comment] 2017-03-23 16:27
[from](https://github.com/unicef/etools/issues/578) @torbent 

If TA not required:

- Introduce optional “submit for approval” flow on save.
- for International Travel, approval is still mandatory.
- Itinerary optional when TA not required.
- DSA shall always be 0 when TA not Required.

**Comment by paragonHex** [comment] 2017-04-05 13:15
@simon-the-sloth Please make sure to do the permission-matrix changes!

**Comment by robertavram** [comment] 2017-04-19 14:14
@simon-the-sloth, @torbent, @janpanchalingam1 On the backend branch I notice that we're 
 building the ability to "Complete" a trip without saving it first .. The workflow diagram does not show that.. I was trying to verify this against a requirement. I can't find the requirement for this..

**Comment by janpanchalingam1** [comment] 2017-04-26 18:02
@robertavram from my understanding there isn't a requirement other than discussion within the Budapest meeting. I am building the updated specifications currently.

**Comment by janpanchalingam1** [comment] 2017-05-04 14:12
@paragonHex @simon-the-sloth after testing, it seems that the '“submit for approval” flow on save' does not occur. The workflow goes only from planned to complete.

**Comment by simon-the-sloth** [comment] 2017-05-05 11:07
@janpanchalingam1 We tried to reproduce but was not able to do the submit for approval flaw.
The missing optional itinerary issue is valid, @paragonHex is working on it.

**Comment by paragonHex** [comment] 2017-05-08 14:01
@janpanchalingam1 @anusenan
The new flow according to specification:
![nota](https://cloud.githubusercontent.com/assets/10398122/25807380/ecc5940e-3406-11e7-9cf0-47da82631399.jpg)

This is the list of the task we gathered, based on how the system is currently working.
    - Ability to save a trip before submission/completion (keep it as planned)
    - Adding one state `Processed`, just before the current `Completed`
        -- András has an Idea how to solve the UI on the side status indicator,
           wouldn’t hurt asking the designer though
        -- A new part of the permission matrix should be made
        -- The trip should be saveable in this `Processed` state, allowing to change the action points,
           reports, and uploads (2nd tab)
    - The e-mail notification of the supervisor should always happen now, regardless of trip
       submittance, also it should move before the trip reaches completed state
    - Aligning and testing all the actions/state transitions that are currently there with
       the new workflow/matrix

**Comment by janpanchalingam1** [comment] 2017-05-08 15:04
@paragonHex the above is correct except please do not add a processed stage. The trip can stay as 'approved'. Let me know if this causes errors for engineering.

**Comment by paragonHex** [comment] 2017-05-09 08:59
@janpanchalingam1
Sure, we can show it on the front-end as approved, but the back-end has to have a new state, right @simon-the-sloth ?
It may still cause confusion in case of non-international trips that doesn't need approval. Should we fake 'approved' state there too?

**Comment by janpanchalingam1** [comment] 2017-05-09 12:46
@paragonHex in the case for the non-international trip, wouldn't the states go from Planned > Submitted > Complete as per the workflow (without processed)? I'm not sure how this would look on the engineering side and can loop in our team if needed.

**Comment by simon-the-sloth** [comment] 2017-05-09 12:53
@janpanchalingam1 All the new flowcharts including a step called "Processed" and we updated the new flow proposal according to that. If there is no need for processed state, please update the flowchart you sent us by removing it to avoid any confusion.

**Comment by janpanchalingam1** [comment] 2017-05-09 13:10
Yes. Please see below and let me know if there is anything that is unclear.
[Waffle 164.pdf](https://github.com/unicef/etools-issues/files/986673/Waffle.164.pdf)

**Comment by simon-the-sloth** [comment] 2017-05-09 13:19
The last step is still a bit vague. If a trip reaches the state Completed, from that point, that will be immutable. If there is a need for action point editing or document upload, then the trip has to go into another state before reaching completed. So basically on the flowchart you sent, in the completed column only the grey END shape should be and any other shape has to go somewhere else.

**Comment by janpanchalingam1** [comment] 2017-05-09 13:34
Here is the updated flow. 
[Waffle 164.pdf](https://github.com/unicef/etools-issues/files/986747/Waffle.164.pdf)

**Comment by simon-the-sloth** [comment] 2017-05-09 14:27
The two submitted states are the same or should be different? Which state corresponds to Approved draft? We have now the following states in the system:
Planned, Submitted, Rejected, Approved, Completed, Cancelled, Sent for payment, Certification submitted, Certification approved, Certification rejected, Certified, Completed

**Comment by janpanchalingam1** [comment] 2017-05-09 14:50
Approved draft corresponds to the traveler's ability to add action points and a report and click 'Save' until they would like to 'Complete' where it is immutable. It would not change the state, only the ability to amend the report tab until completed.

**Comment by kasfaw** [comment] 2017-05-09 17:27
@simon-the-sloth a few things to your question:
1. The traveler should be asked if a supervisor approval is required IF (Action = "Save & Submit) AND "International Trip" = 0); if the traveler simply saves a planned trip, he should not recieve the "supervisor approval?" prompt
2. The supervisor should be prompted to Approve or Reject a trip IF ("Supervisor Approval" = Yes OR "International Trip" = 0)
3. Once a trip is approved, the state should be marked as Approved
4. A trip should be marked as "Completed" once the traveller select an a pproved trip to be completed AND a trip report exists
5. A traveler can cancel a non-TA trip IF status is (Planned, Approved, Rejected)

So, there are 5 states in non-TA (Planned, Canceled, Approved, Rejected, Completed)

**Comment by simon-the-sloth** [comment] 2017-05-10 14:45
@janpanchalingam1 The problem is that if the ability of this action does not match with the abilities of any other state, then it is considered a new state from engineering point of view. So if the abilities should be limited to the action points and report in the approved state, then we have to create a new one which might be called the same but has to has the new functionality/abilities because the permission matrix cannot differentiate between the two status (approval ta required or approval ta not required).

@kasfaw 1: What should happen if the traveler clicks the "No approval required" button? In which state should the trip go?
2: This one is clear.
3: This needs comments. If it will be "Approved", then the users abilities will be exactly the same as the current flow. If the user has to be limited to action point and report modification, then we have to create a new state which can have the corresponding permission matrix set.
4: This one is clear.
5: This one is clear.

Unfortunately we have to keep a few things in mind which came from engineering decisions and how the system is working now. One is the coupling between states and permission matrix. One travel state has only one set of permissions attached to it. It's not possible to have the same state but different permissions based on some fields of the travel (TA true or false). Since the post approval/post save and submit (if no approval required) has to have a new set of permissions to allow action point/report modification, I don't see any other solution than introducing a new state. The trick what can be done here is naming the new state same like on of the existing ones (end user will see like the trip is in approved state but in reality it will be in processed). This is just cosmetics, but might be the solution which satisfies business and engineering needs at the same time.

**Comment by simon-the-sloth** [comment] 2017-05-10 15:02
Our current understanding of the flow: 
[NonTA flow.pdf](https://github.com/unicef/etools-issues/files/990241/NonTA.flow.pdf)

**Comment by kasfaw** [comment] 2017-05-10 21:35
[NonTA.flow.2.pdf](https://github.com/unicef/etools-issues/files/991288/NonTA.flow.2.pdf)
@simon-the-sloth business owner adn @janpanchalingam1 have gone through and approved workflow. I have added in brackets the various states to each step and the ability to cancel and/or save at each step. Hope this helps.

**Comment by janpanchalingam1** [comment] 2017-05-16 02:08
@simon-the-sloth are we able to make the itinerary not mandatory but optional?

**Comment by lordfuoco** [comment] 2017-05-16 06:02
@janpanchalingam1 we already did so, of course only for TA not required trips

**Comment by janpanchalingam1** [comment] 2017-05-19 14:06
Failed.
Browser: Chrome and IE
Workspace: Kyrgyzstan
Link: https://etools-staging.unicef.org/t2f/edit-travel/188 
1) Traveller created a Non-TA trip and submitted to supervisor for approval
2) Supervisor cannot approve, only can complete, reject or cancel trip.
3) Supervisor clicks complete and trip is marked as completed.
![screen shot 2017-05-19 at 9 59 43 am](https://cloud.githubusercontent.com/assets/26144740/26251244/a4abcc70-3c7a-11e7-8f0e-a8efc22acb47.png)

**Comment by janpanchalingam1** [comment] 2017-05-19 14:20
1) Supervisor rejects trip
2) Traveller submits to Supervisor for approval but the button says 'Save' not 'Save and Submit'
![image](https://cloud.githubusercontent.com/assets/26144740/26251872/b6221a5c-3c7c-11e7-9b45-790ac8c50e23.png)

**Comment by janpanchalingam1** [comment] 2017-05-19 16:48
Failed.
Browser: Chrome and IE
Workspace: Kyrgyzstan 
Link:
1) Traveller creates a non-TA trip and submitted for approval
2) Supervisor approved non-TA
3) Traveller cannot complete trip or add report as the complete button is not available 
![image](https://cloud.githubusercontent.com/assets/26144740/26258107/39f8808c-3c91-11e7-9840-9f6a03954d81.png)

**Comment by kasfaw** [comment] 2017-05-19 19:03
@torbent @lordfuoco @simon-the-sloth this could be a result of the "invoice disable" function that pushes approved trips directly to sent for payment. If we are able to enable a traveller to have the same permissions/available actions as whats available in Approved for non-TA, this should fix the problem.

**Comment by ilcsik** [comment] 2017-05-22 12:11
@kasfaw @robertavram @janpanchalingam1 this issue is fixed in https://github.com/unicef/etools/pull/674, can you please kindly check when you have a chance (staging needs to be updated)?

**Comment by janpanchalingam1** [comment] 2017-05-23 13:00
Pass!

**Closed** 2017-08-08 15:05 UTC
Labels: Done, enhancement, High, Maintenance, Trips
