### ISSUE TITLE
Overview Pages in PDs does not seem reflect the dates that are on the details tab

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#136] opened 2017-03-15 07:56 UTC
I can see that the overview tab for SXB PD Gaziantep/PCA/002/2015/UOSSM does not show the same dates as the detail tab. Please compare the start and end date on the detail tab and the "timeline" dates on the overview tab.

**Comment by evrimm** [comment] 2017-03-31 20:12
@robertavram @mpawlowski85 This issue seems to be resolved, i just checked the referenced PD. The interesting thing is if you look at the details on github, you'll see that although Rob added Done and removed Needs Review, wafflebot did the opposite. @anusenan this seems like the waffle failure we were talking about earlier.

**Comment by anusenan** [comment] 2017-04-03 15:48
Response from Waffle team:

Sorry for the late reply, we're typically in the office from 9-5 MST Monday through Friday. 
So after taking a look at this, it would appear that this issue was referenced in the PR #197 (the wording used was Fixes unicef/etools-issues#136). Any time a issue is referenced within a PR, it is picked up by WaffleBot and moved to the appropriate column. For example, when you reference an issue in a newly created PR name, that issue will be moved to the New Collaborator PR column, then moved to the appropriate column when it is merged. 
On PR #197, it appears that the PR was renamed. Because it was renamed, Waffle recognized this as a 'new PR', so it moved issue #136 to your New Collaborator PR column which is your Needs Review column. Then, when the PR was merged, the issue was moved to your 'Done' column, which is why the labels are added and removed. This is not the expected behavior, we'll have to look into this bug. 

@robertavram - can you confirm if this is the case?

**Closed** 2017-05-02 20:47 UTC
Labels: Done, Medium, PD/SSFA TOR, PMP
