### ISSUE TITLE
404 and 500 error on "Generate a PCA" Special characters

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#755] opened 2017-09-27 17:49 UTC

**Comment by csabadenes** [comment] 2017-09-28 12:51
I was unable to reproduce  these issues on existing PCA agreements. We managed to reproduce the "404 error"  only on the "Add Agreement" screen, when the "Generate" button is pressed before the agreement is saved. I believe this issue will be handled by the frontend team.

Can you please provide more details about the "500 error",  and the "special characters" issue? Thanks.

**Comment by ntrncic** [comment] 2017-09-28 13:21
@aldohunicef we need a better description of the error. Such as workspace, and agreement id and steps to re-poroduce.

**Comment by aldohunicef** [comment] 2017-09-29 17:30
[PCA_404Error.zip](https://github.com/unicef/etools-issues/files/1345159/PCA_404Error.zip)

**Comment by aldohunicef** [comment] 2017-09-29 17:34
Please see a set of screenshots in the zip file.
There is a step by step description

@csabadenes I don't know if it is related to Special Characters, that is what @ntrncic suggested after he saw the issue in-situ. 
This is NOT related to unsaved agreements.  ... this error happens after agreements are SAVED. 
This happens in all workspaces and only with random partners. @ntrncic thinks is related to Special Characters.

**Comment by ntrncic** [comment] 2017-09-29 20:16
it's been fixed in staging.

**Comment by mpawlowski85** [comment] 2017-10-04 14:55
I was now able to generate the PCA

![image](https://user-images.githubusercontent.com/26120371/31182650-7654cb30-a8f2-11e7-900e-0673edd52ef0.png)

**Closed** 2017-11-01 16:41 UTC
Labels: Agreements, backend, PMP, PMP-Redesign
