### ISSUE TITLE
Trips after "cancel" still appear HACT Dashboard

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#858] opened 2017-10-23 18:53 UTC
in Liberia and Burkina . After deleting the trips, they still appear in the HACT dashboard.

**Comment by ShrinivasPuranik** [comment] 2017-10-24 14:35
Test the count and document the issues. Determine Root cause to determine the bug,

Investigate if it needs to be part of New HACT future state requirements.

**Comment by janpanchalingam1** [comment] 2017-10-25 17:35
Tested in Jordan. Tested trip by cancelling a submitted and approved trip. Neither counts in the dash. The only trips that are counted in the dash are the ones marked as completed and if the date of visit is in the past.

**Closed** 2017-10-25 17:36 UTC
Labels: Dashboard, invalid
