### ISSUE TITLE
(UAT) PD Status to signed - No CP Structure

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-issues#770] opened 2017-09-27 19:53 UTC
Status of the document transition to signed while CP structure is missing and the error message is wrong. CP Structure has an asterisk mark but this is field is not being validated as a mandatory field.

**Comment by KKaselkar** [comment] 2017-09-27 19:55
![untitled](https://user-images.githubusercontent.com/32198614/30934656-3fd9a9c8-a39c-11e7-8ec2-42ab64fd76f9.png)

**Comment by ewheeler** [comment] 2017-09-28 16:34
@KKaselkar please provide details to reproduce. screenshot is not legible

**Comment by KKaselkar** [comment] 2017-09-28 21:05
steps to reproduce the error:
1)Add SSFA
2) Enter the  Partnership information details
3) Enter Start Date and End Date for PD or SSFA Details 
4) CP Structure is already pre populated today and doesnt have a asterisk mark.
Could you please explain what changes were done on this page from yesterday ?
screenshot below:
![1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c925e34d3dcd001231c900/125516c66e82c728ace21e0d46b9d6d6619291a685ecbc57e607b2c1714470277800f57974d0e07fe7462a515e0d46fa105b5e56e0ebcb7af8e2632dd3165eafc3674d75ce3710a9b88419bc03bd248f498cb2aec7.png)

**Comment by adi130987** [comment] 2017-09-29 08:22
@KKaselkar I really do not understand the issue here. So, your yesterday low resolution blurry screenshot message says: `This intervention has an old/expired CP Structure!`. Are you sure you did not opened a PD/SSFA that was previously created, got to signed status, and the CP Structure is expired?

What's the environment you tested on? https://etools-staging.unicef.org or https://etools-dev.unicef.org? What is the ID of this PD?

Nothing has changed to that field since yesterday(or this or last week).

**Comment by mpawlowski85** [comment] 2017-10-02 21:13
Issue cannot be reproduced. I am marking it as invalid and closing until it is reported again.

**Closed by mpawlowski85** 2017-10-02 21:13 UTC
Labels: invalid, PMP-Redesign
