### ISSUE TITLE
IE: Unable to add new agreement

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#586] opened 2017-08-08 18:36 UTC
Browser: IE
Workspace: All

1) User clicks 'add agreement'
2) Page does not load. 
3) Refreshed twice, page does not load. See screenshot.

**Comment by janpanchalingam1** [comment] 2017-08-08 18:36
![image](https://user-images.githubusercontent.com/26144740/29088413-fa65865e-7c46-11e7-9bcb-10e11e8964a5.png)

**Comment by acory** [comment] 2017-08-08 19:28
Duplicate of  unicef/etools-issues#584

**Closed by acory** 2017-08-08 19:28 UTC
Labels: Agreements, bug, High, PMP-Redesign
