### ISSUE TITLE
Long loading time on PMP for Sierra Leone FO

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-issues#207] opened 2017-03-27 07:59 UTC
Took over 6 minutes to load PMP from a Sierra Leone FO

**Comment by ewheeler** [comment] 2017-03-27 15:43
@kasfaw is this consistent behaviour for you? loads in just a few second for both myself and @robertavram

**Comment by mpawlowski85** [comment] 2017-03-28 22:28
Cannot reproduce the issue - it is now marked as invalid until reported again.

**Closed** 2017-04-18 13:31 UTC
Labels: bug, invalid, PMP
