### ISSUE TITLE
Travel activity export : Fields are not ordered as per specification document

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#62] opened 2017-03-08 21:20 UTC

**Comment by anusenan** [comment] 2017-03-08 21:20
![image](https://cloud.githubusercontent.com/assets/25492170/23724554/23c58688-041b-11e7-96b9-50bad5b5fbbb.png)

**Comment by kasfaw** [comment] 2017-03-15 12:48
duplicate of https://github.com/unicef/etools-issues/issues/76

**Closed** 2017-03-23 15:47 UTC
Labels: duplicate
