### ISSUE TITLE
More user friendly way to show that more than 1 PCA not allowed in single country programme.

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#44] opened 2017-03-08 16:24 UTC

**Comment by ntrncic** [comment] 2017-03-14 19:07
@anusenan  i think this is more than one PCA allowed for agreement.

**Comment by anusenan** [comment] 2017-03-14 20:23
@mpawlowski85 can you please throw some light on this?

**Comment by mpawlowski85** [comment] 2017-03-14 22:02
@ntrncic @anusenan 
You can only have 1 PCA per vendor per CP cycle. We currently have a validation, where if there already is a PCA with a particular partner in within a country programme, then the 2nd PCA we set up with that partner will not get active (although all activation criteria are met). We need to find a more user-friendly way of saying that there is another PCA with this partner within the CP and thus no more PCA can be active with this Country Programme.

**Comment by robertavram** [comment] 2017-03-21 13:10
not a bug -> feature request

**Comment by robertavram** [comment] 2017-03-27 15:09
We need to agree on how to show the "more user friendly" message before we start work on it. This can have impact on how we serialize data for the front end.

**Comment by mpawlowski85** [comment] 2017-03-27 15:12
@evrimm can you please jump in on this as well?

**Comment by evrimm** [comment] 2017-03-27 15:16
@robertavram @mpawlowski85 I will come up with a way.

**Comment by evrimm** [comment] 2017-04-04 13:10
@robertavram @mpawlowski85 @ntrncic don't start work on this yet. Next week we will talk about PCA and SSFA validations with business owners, this issue might extend to include some other validations too.

**Comment by mpawlowski85** [comment] 2017-04-11 13:18
Moving this back to inbox, as more clarifications are needed.

**Comment by mpawlowski85** [comment] 2017-04-24 23:09
specs contained elsewhere - closing the issue.

**Closed by mpawlowski85** 2017-04-24 23:09 UTC
Labels: invalid
