### ISSUE TITLE
Error Msg vague: Saving a New Govt-In-Simple while leaving Ref no blank

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#19] opened 2017-03-07 21:26 UTC

**Comment by anusenan** [comment] 2017-03-07 21:27
When Saving a New Govt-In-Simple while leaving Ref no blank, the message is: 
Errors occurred: Field number(0) - This field may not be null

Please make the message more specific.

**Comment by adi130987** [comment] 2017-03-14 07:46
This type of messages come from backend, we could add a validation with a more specific  message on frontend.

**Comment by kasfaw** [comment] 2017-03-15 09:09
Can the error message read: "Please enter a unique reference number for your Government Work Plan"

**Comment by robertavram** [comment] 2017-03-16 00:03
cannot replicate. Please try to replicate.. remove issue from backlog if cleared.

**Comment by daniel-tabarcea** [comment] 2017-03-17 11:46
I've tried to replicate it and failed. It works fine.

**Comment by ewheeler** [comment] 2017-03-23 16:21
can't reproduce, so closing

**Closed by ewheeler** 2017-03-23 16:21 UTC
Labels: GovInSimple, invalid, PMP
