### ISSUE TITLE
Unable to complete migrated trips due to un-editable report field

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#276] opened 2017-04-16 10:36 UTC
Unable to add report for trips in status Approve or Sent for Payment prior to March 6

**Comment by janpanchalingam1** [comment] 2017-04-16 10:37
![upload_4_10_2017_at_4_07_37_pm](https://cloud.githubusercontent.com/assets/26144740/25070529/203f99b4-226f-11e7-8992-cc4a931b7950.png)
![upload_4_10_2017_at_4_06_56_pm](https://cloud.githubusercontent.com/assets/26144740/25070531/21e2d164-226f-11e7-900c-3af66dcbb350.png)

**Comment by torbent** [comment] 2017-05-08 09:18
@janpanchalingam1 we are unable to reproduce this at the dev-server, and we lack access to staging atm. See if you can reproduce this on dev first. If you get same result, please send us more info about the setup on how you recreated this ( user, role, os, browser ).

**Comment by janpanchalingam1** [comment] 2017-05-08 13:19
@anusenan I don't have access to dev. Are you able to test this?

**Comment by anusenan** [comment] 2017-05-10 16:51
@janpanchalingam1 - Puli is unable to recreate this issue in staging. I tried in Sierra Leone for dates older than Mar 6 and it allows me to add reports once trip is Approved.

**Comment by janpanchalingam1** [comment] 2017-05-14 13:29
Looping in @aldohunicef as this was issues reported by the users to see if there is any supporting screenshots or specific trip links we can refer to

**Comment by kasfaw** [comment] 2017-05-18 19:43
@torbent this can not be reproduced and saving works as desired. please close this issue

**Closed** 2017-05-25 20:46 UTC
Labels: invalid
