### ISSUE TITLE
UNICEF Focal Points List overlapps (ALM 133)

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#405] opened 2017-06-02 18:52 UTC
UNICEF Focal Points List box search field is overlapped with eTools banner on the top 

Browser: IE and Chrome
Workspace: Jordan and Philipines 
Please find attached Screenshot

**Comment by mpawlowski85** [comment] 2017-06-02 18:52
![alm_snapshot](https://cloud.githubusercontent.com/assets/26120371/26740344/2425d206-47a3-11e7-849f-3f701ee7719a.jpg)

**Comment by acory** [comment] 2017-08-10 10:23
Duplicate of #570

**Closed by acory** 2017-08-10 10:23 UTC
Labels: Backlog, bug, Medium, PD/SSFA TOR, PMP

**Comment by ntrncic** [comment] 2017-08-10 15:01
moving to closed as it's a duplicate
