### ISSUE TITLE
IE / PD Planned Budget

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#318] opened 2017-04-26 21:00 UTC
1. Go to eTools (Staging)
2. Go to PMP / PD
3. Click to Add new PD
4. Click on Planned Budget + Button 
5. User see only "Totals of budget" (Partnership Manager)
User should see the rest of the fields

**Comment by aldohunicef** [comment] 2017-04-26 21:00
![image](https://cloud.githubusercontent.com/assets/26142645/25456771/dce9cba4-2aa1-11e7-8330-d2e5c23952a0.png)

**Comment by adi130987** [comment] 2017-04-27 12:42
@aldohunicef I can not reproduce it on https://etools-dev.unicef.org and on staging I do not have an account to be able to login. Can you put a screenshot with the IE11 console? I need to know if there are console errors logged when this happens.

**Comment by mpawlowski85** [comment] 2017-04-27 15:29
@adi130987 
I also cannot reproduce it.  @aldohunicef can you please get on skype with the user and follow the user step by step to see if it can be reproduced? If yes, then we will need the dump from the console. If the user does not experience it anymore, then this is an example of erratic behaviour that will have to be investigated. Thanks!

**Comment by adi130987** [comment] 2017-07-24 08:35
Planned Budget has changed completely in pmp redesign functionality.

**Comment by adi130987** [comment] 2017-07-24 08:35
@mpawlowski85 can we close this one?

**Comment by mpawlowski85** [comment] 2017-07-24 14:56
@adi130987 yup - I am closing this one.

**Closed by mpawlowski85** 2017-07-24 14:56 UTC
Labels: bug, High, InDev, PD/SSFA TOR, PMP
