### ISSUE TITLE
Console error on Pd overview page refresh

### ISSUE THREAD

**Issue by acory** [unicef/etools-issues#747] opened 2017-09-25 10:23 UTC
Env: Dev
![pd_ov](https://user-images.githubusercontent.com/26309191/30804131-ec5565ba-a1f4-11e7-845b-3a5589650385.png)

**Comment by roxanavlad** [comment] 2017-09-26 13:40
@acory , this is fixed on dev

**Comment by mpawlowski85** [comment] 2017-10-09 14:16
I cannot reproduce the issue. This is now passed until reported again.

**Closed** 2017-11-01 16:40 UTC
Labels: bug, Front End, PD/SSFA TOR, PMP
